name: Netease Auto Clock In

on:
  # push 到 main 分支的时候会触发打卡
  push:
    branches:
      - master
  # 定时打卡
  schedule:
    # 下方代码第一段数字表示第 30 分钟，第二段数字表示第 0 小时和第 22 小时，但是这个时间比北京时间晚 8 小时，所以当前打卡的时间为 6 点 30 分和 8 点 30 分。
    # 免费版的 Github Action 定时执行会有延迟，大概是延迟半小时到一小时不等。两次打卡时间不宜过短。
    - cron: 30 22,0 * * *
    
env:
  PUSH_KEY: ${{ secrets.PUSH_KEY }}
  ACCOUNT: ${{ secrets.ACCOUNT }}
  PASSWORD: ${{ secrets.PASSWORD }}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
              
            - name: Set up Python 3.9
              uses: actions/setup-python@v2
              with:
                python-version: 3.9
              
            - name: Run Script
              run: python index.py
